<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $countries = [
            ['Afghanistan', 'Islamic Republic of Afghanistan', 'AF', 'AFG', '004', '93', '.af'],
            ['Aland Islands', '&Aring;land Islands', 'AX', 'ALA', '248', '358', '.ax'],
            ['Albania', 'Republic of Albania', 'AL', 'ALB', '008', '355', '.al'],
            ['Algeria', 'People\'s Democratic Republic of Algeria', 'DZ', 'DZA', '012', '213', '.dz'],
            ['American Samoa', 'American Samoa', 'AS', 'ASM', '016', '1+684', '.as'],
            ['Andorra', 'Principality of Andorra', 'AD', 'AND', '020', '376', '.ad'],
            ['Angola', 'Republic of Angola', 'AO', 'AGO', '024', '244', '.ao'],
            ['Anguilla', 'Anguilla', 'AI', 'AIA', '660', '1+264', '.ai'],
            ['Antarctica', 'Antarctica', 'AQ', 'ATA', '010', '672', '.aq'],
            ['Antigua and Barbuda', 'Antigua and Barbuda', 'AG', 'ATG', '028', '1+268', '.ag'],
            ['Argentina', 'Argentine Republic', 'AR', 'ARG', '032', '54', '.ar'],
            ['Armenia', 'Republic of Armenia', 'AM', 'ARM', '051', '374', '.am'],
            ['Aruba', 'Aruba', 'AW', 'ABW', '533', '297', '.aw'],
            ['Australia', 'Commonwealth of Australia', 'AU', 'AUS', '036', '61', '.au'],
            ['Austria', 'Republic of Austria', 'AT', 'AUT', '040', '43', '.at'],
            ['Azerbaijan', 'Republic of Azerbaijan', 'AZ', 'AZE', '031', '994', '.az'],
            ['Bahamas', 'Commonwealth of The Bahamas', 'BS', 'BHS', '044', '1+242', '.bs'],
            ['Bahrain', 'Kingdom of Bahrain', 'BH', 'BHR', '048', '973', '.bh'],
            ['Bangladesh', 'People\'s Republic of Bangladesh', 'BD', 'BGD', '050', '880', '.bd'],
            ['Barbados', 'Barbados', 'BB', 'BRB', '052', '1+246', '.bb'],
            ['Belarus', 'Republic of Belarus', 'BY', 'BLR', '112', '375', '.by'],
            ['Belgium', 'Kingdom of Belgium', 'BE', 'BEL', '056', '32', '.be'],
            ['Belize', 'Belize', 'BZ', 'BLZ', '084', '501', '.bz'],
            ['Benin', 'Republic of Benin', 'BJ', 'BEN', '204', '229', '.bj'],
            ['Bermuda', 'Bermuda Islands', 'BM', 'BMU', '060', '1+441', '.bm'],
            ['Bhutan', 'Kingdom of Bhutan', 'BT', 'BTN', '064', '975', '.bt'],
            ['Bolivia', 'Plurinational State of Bolivia', 'BO', 'BOL', '068', '591', '.bo'],
            ['Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '535', '599', '.bq'],
            ['Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BA', 'BIH', '070', '387', '.ba'],
            ['Botswana', 'Republic of Botswana', 'BW', 'BWA', '072', '267', '.bw'],
            ['Bouvet Island', 'Bouvet Island', 'BV', 'BVT', '074', NULL, '.bv'],
            ['Brazil', 'Federative Republic of Brazil', 'BR', 'BRA', '076', '55', '.br'],
            ['British Indian Ocean Territory', 'British Indian Ocean Territory', 'IO', 'IOT', '086', '246', '.io'],
            ['Brunei', 'Brunei Darussalam', 'BN', 'BRN', '096', '673', '.bn'],
            ['Bulgaria', 'Republic of Bulgaria', 'BG', 'BGR', '100', '359', '.bg'],
            ['Burkina Faso', 'Burkina Faso', 'BF', 'BFA', '854', '226', '.bf'],
            ['Burundi', 'Republic of Burundi', 'BI', 'BDI', '108', '257', '.bi'],
            ['Cambodia', 'Kingdom of Cambodia', 'KH', 'KHM', '116', '855', '.kh'],
            ['Cameroon', 'Republic of Cameroon', 'CM', 'CMR', '120', '237', '.cm'],
            ['Canada', 'Canada', 'CA', 'CAN', '124', '1', '.ca'],
            ['Cape Verde', 'Republic of Cape Verde', 'CV', 'CPV', '132', '238', '.cv'],
            ['Cayman Islands', 'The Cayman Islands', 'KY', 'CYM', '136', '1+345', '.ky'],
            ['Central African Republic', 'Central African Republic', 'CF', 'CAF', '140', '236', '.cf'],
            ['Chad', 'Republic of Chad', 'TD', 'TCD', '148', '235', '.td'],
            ['Chile', 'Republic of Chile', 'CL', 'CHL', '152', '56', '.cl'],
            ['China', 'People\'s Republic of China', 'CN', 'CHN', '156', '86', '.cn'],
            ['Christmas Island', 'Christmas Island', 'CX', 'CXR', '162', '61', '.cx'],
            ['Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'CC', 'CCK', '166', '61', '.cc'],
            ['Colombia', 'Republic of Colombia', 'CO', 'COL', '170', '57', '.co'],
            ['Comoros', 'Union of the Comoros', 'KM', 'COM', '174', '269', '.km'],
            ['Congo', 'Republic of the Congo', 'CG', 'COG', '178', '242', '.cg'],
            ['Cook Islands', 'Cook Islands', 'CK', 'COK', '184', '682', '.ck'],
            ['Costa Rica', 'Republic of Costa Rica', 'CR', 'CRI', '188', '506', '.cr'],
            ['Cote d\'ivoire (Ivory Coast)', 'Republic of C&ocirc;te D\'Ivoire (Ivory Coast)', 'CI', 'CIV', '384', '225', '.ci'],
            ['Croatia', 'Republic of Croatia', 'HR', 'HRV', '191', '385', '.hr'],
            ['Cuba', 'Republic of Cuba', 'CU', 'CUB', '192', '53', '.cu'],
            ['Curacao', 'Cura&ccedil;ao', 'CW', 'CUW', '531', '599', '.cw'],
            ['Cyprus', 'Republic of Cyprus', 'CY', 'CYP', '196', '357', '.cy'],
            ['Czech Republic', 'Czech Republic', 'CZ', 'CZE', '203', '420', '.cz'],
            ['Democratic Republic of the Congo', 'Democratic Republic of the Congo', 'CD', 'COD', '180', '243', '.cd'],
            ['Denmark', 'Kingdom of Denmark', 'DK', 'DNK', '208', '45', '.dk'],
            ['Djibouti', 'Republic of Djibouti', 'DJ', 'DJI', '262', '253', '.dj'],
            ['Dominica', 'Commonwealth of Dominica', 'DM', 'DMA', '212', '1+767', '.dm'],
            ['Dominican Republic', 'Dominican Republic', 'DO', 'DOM', '214', '1+809, 8', '.do'],
            ['Ecuador', 'Republic of Ecuador', 'EC', 'ECU', '218', '593', '.ec'],
            ['Egypt', 'Arab Republic of Egypt', 'EG', 'EGY', '818', '20', '.eg'],
            ['El Salvador', 'Republic of El Salvador', 'SV', 'SLV', '222', '503', '.sv'],
            ['Equatorial Guinea', 'Republic of Equatorial Guinea', 'GQ', 'GNQ', '226', '240', '.gq'],
            ['Eritrea', 'State of Eritrea', 'ER', 'ERI', '232', '291', '.er'],
            ['Estonia', 'Republic of Estonia', 'EE', 'EST', '233', '372', '.ee'],
            ['Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ET', 'ETH', '231', '251', '.et'],
            ['Falkland Islands (Malvinas)', 'The Falkland Islands (Malvinas)', 'FK', 'FLK', '238', '500', '.fk'],
            ['Faroe Islands', 'The Faroe Islands', 'FO', 'FRO', '234', '298', '.fo'],
            ['Fiji', 'Republic of Fiji', 'FJ', 'FJI', '242', '679', '.fj'],
            ['Finland', 'Republic of Finland', 'FI', 'FIN', '246', '358', '.fi'],
            ['France', 'French Republic', 'FR', 'FRA', '250', '33', '.fr'],
            ['French Guiana', 'French Guiana', 'GF', 'GUF', '254', '594', '.gf'],
            ['French Polynesia', 'French Polynesia', 'PF', 'PYF', '258', '689', '.pf'],
            ['French Southern Territories', 'French Southern Territories', 'TF', 'ATF', '260', NULL, '.tf'],
            ['Gabon', 'Gabonese Republic', 'GA', 'GAB', '266', '241', '.ga'],
            ['Gambia', 'Republic of The Gambia', 'GM', 'GMB', '270', '220', '.gm'],
            ['Georgia', 'Georgia', 'GE', 'GEO', '268', '995', '.ge'],
            ['Germany', 'Federal Republic of Germany', 'DE', 'DEU', '276', '49', '.de'],
            ['Ghana', 'Republic of Ghana', 'GH', 'GHA', '288', '233', '.gh'],
            ['Gibraltar', 'Gibraltar', 'GI', 'GIB', '292', '350', '.gi'],
            ['Greece', 'Hellenic Republic', 'GR', 'GRC', '300', '30', '.gr'],
            ['Greenland', 'Greenland', 'GL', 'GRL', '304', '299', '.gl'],
            ['Grenada', 'Grenada', 'GD', 'GRD', '308', '1+473', '.gd'],
            ['Guadaloupe', 'Guadeloupe', 'GP', 'GLP', '312', '590', '.gp'],
            ['Guam', 'Guam', 'GU', 'GUM', '316', '1+671', '.gu'],
            ['Guatemala', 'Republic of Guatemala', 'GT', 'GTM', '320', '502', '.gt'],
            ['Guernsey', 'Guernsey', 'GG', 'GGY', '831', '44', '.gg'],
            ['Guinea', 'Republic of Guinea', 'GN', 'GIN', '324', '224', '.gn'],
            ['Guinea-Bissau', 'Republic of Guinea-Bissau', 'GW', 'GNB', '624', '245', '.gw'],
            ['Guyana', 'Co-operative Republic of Guyana', 'GY', 'GUY', '328', '592', '.gy'],
            ['Haiti', 'Republic of Haiti', 'HT', 'HTI', '332', '509', '.ht'],
            ['Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'HM', 'HMD', '334', NULL, '.hm'],
            ['Honduras', 'Republic of Honduras', 'HN', 'HND', '340', '504', '.hn'],
            ['Hong Kong', 'Hong Kong', 'HK', 'HKG', '344', '852', '.hk'],
            ['Hungary', 'Hungary', 'HU', 'HUN', '348', '36', '.hu'],
            ['Iceland', 'Republic of Iceland', 'IS', 'ISL', '352', '354', '.is'],
            ['India', 'Republic of India', 'IN', 'IND', '356', '91', '.in'],
            ['Indonesia', 'Republic of Indonesia', 'ID', 'IDN', '360', '62', '.id'],
            ['Iran', 'Islamic Republic of Iran', 'IR', 'IRN', '364', '98', '.ir'],
            ['Iraq', 'Republic of Iraq', 'IQ', 'IRQ', '368', '964', '.iq'],
            ['Ireland', 'Ireland', 'IE', 'IRL', '372', '353', '.ie'],
            ['Isle of Man', 'Isle of Man', 'IM', 'IMN', '833', '44', '.im'],
            ['Israel', 'State of Israel', 'IL', 'ISR', '376', '972', '.il'],
            ['Italy', 'Italian Republic', 'IT', 'ITA', '380', '39', '.jm'],
            ['Jamaica', 'Jamaica', 'JM', 'JAM', '388', '1+876', '.jm'],
            ['Japan', 'Japan', 'JP', 'JPN', '392', '81', '.jp'],
            ['Jersey', 'The Bailiwick of Jersey', 'JE', 'JEY', '832', '44', '.je'],
            ['Jordan', 'Hashemite Kingdom of Jordan', 'JO', 'JOR', '400', '962', '.jo'],
            ['Kazakhstan', 'Republic of Kazakhstan', 'KZ', 'KAZ', '398', '7', '.kz'],
            ['Kenya', 'Republic of Kenya', 'KE', 'KEN', '404', '254', '.ke'],
            ['Kiribati', 'Republic of Kiribati', 'KI', 'KIR', '296', '686', '.ki'],
            ['Kosovo', 'Republic of Kosovo', 'XK', NULL, NULL, '381', NULL],
            ['Kuwait', 'State of Kuwait', 'KW', 'KWT', '414', '965', '.kw'],
            ['Kyrgyzstan', 'Kyrgyz Republic', 'KG', 'KGZ', '417', '996', '.kg'],
            ['Laos', 'Lao People\'s Democratic Republic', 'LA', 'LAO', '418', '856', '.la'],
            ['Latvia', 'Republic of Latvia', 'LV', 'LVA', '428', '371', '.lv'],
            ['Lebanon', 'Republic of Lebanon', 'LB', 'LBN', '422', '961', '.lb'],
            ['Lesotho', 'Kingdom of Lesotho', 'LS', 'LSO', '426', '266', '.ls'],
            ['Liberia', 'Republic of Liberia', 'LR', 'LBR', '430', '231', '.lr'],
            ['Libya', 'Libya', 'LY', 'LBY', '434', '218', '.ly'],
            ['Liechtenstein', 'Principality of Liechtenstein', 'LI', 'LIE', '438', '423', '.li'],
            ['Lithuania', 'Republic of Lithuania', 'LT', 'LTU', '440', '370', '.lt'],
            ['Luxembourg', 'Grand Duchy of Luxembourg', 'LU', 'LUX', '442', '352', '.lu'],
            ['Macao', 'The Macao Special Administrative Region', 'MO', 'MAC', '446', '853', '.mo'],
            ['Macedonia', 'The Former Yugoslav Republic of Macedonia', 'MK', 'MKD', '807', '389', '.mk'],
            ['Madagascar', 'Republic of Madagascar', 'MG', 'MDG', '450', '261', '.mg'],
            ['Malawi', 'Republic of Malawi', 'MW', 'MWI', '454', '265', '.mw'],
            ['Malaysia', 'Malaysia', 'MY', 'MYS', '458', '60', '.my'],
            ['Maldives', 'Republic of Maldives', 'MV', 'MDV', '462', '960', '.mv'],
            ['Mali', 'Republic of Mali', 'ML', 'MLI', '466', '223', '.ml'],
            ['Malta', 'Republic of Malta', 'MT', 'MLT', '470', '356', '.mt'],
            ['Marshall Islands', 'Republic of the Marshall Islands', 'MH', 'MHL', '584', '692', '.mh'],
            ['Martinique', 'Martinique', 'MQ', 'MTQ', '474', '596', '.mq'],
            ['Mauritania', 'Islamic Republic of Mauritania', 'MR', 'MRT', '478', '222', '.mr'],
            ['Mauritius', 'Republic of Mauritius', 'MU', 'MUS', '480', '230', '.mu'],
            ['Mayotte', 'Mayotte', 'YT', 'MYT', '175', '262', '.yt'],
            ['Mexico', 'United Mexican States', 'MX', 'MEX', '484', '52', '.mx'],
            ['Micronesia', 'Federated States of Micronesia', 'FM', 'FSM', '583', '691', '.fm'],
            ['Moldava', 'Republic of Moldova', 'MD', 'MDA', '498', '373', '.md'],
            ['Monaco', 'Principality of Monaco', 'MC', 'MCO', '492', '377', '.mc'],
            ['Mongolia', 'Mongolia', 'MN', 'MNG', '496', '976', '.mn'],
            ['Montenegro', 'Montenegro', 'ME', 'MNE', '499', '382', '.me'],
            ['Montserrat', 'Montserrat', 'MS', 'MSR', '500', '1+664', '.ms'],
            ['Morocco', 'Kingdom of Morocco', 'MA', 'MAR', '504', '212', '.ma'],
            ['Mozambique', 'Republic of Mozambique', 'MZ', 'MOZ', '508', '258', '.mz'],
            ['Myanmar (Burma)', 'Republic of the Union of Myanmar', 'MM', 'MMR', '104', '95', '.mm'],
            ['Namibia', 'Republic of Namibia', 'NA', 'NAM', '516', '264', '.na'],
            ['Nauru', 'Republic of Nauru', 'NR', 'NRU', '520', '674', '.nr'],
            ['Nepal', 'Federal Democratic Republic of Nepal', 'NP', 'NPL', '524', '977', '.np'],
            ['Netherlands', 'Kingdom of the Netherlands', 'NL', 'NLD', '528', '31', '.nl'],
            ['New Caledonia', 'New Caledonia', 'NC', 'NCL', '540', '687', '.nc'],
            ['New Zealand', 'New Zealand', 'NZ', 'NZL', '554', '64', '.nz'],
            ['Nicaragua', 'Republic of Nicaragua', 'NI', 'NIC', '558', '505', '.ni'],
            ['Niger', 'Republic of Niger', 'NE', 'NER', '562', '227', '.ne'],
            ['Nigeria', 'Federal Republic of Nigeria', 'NG', 'NGA', '566', '234', '.ng'],
            ['Niue', 'Niue', 'NU', 'NIU', '570', '683', '.nu'],
            ['Norfolk Island', 'Norfolk Island', 'NF', 'NFK', '574', '672', '.nf'],
            ['North Korea', 'Democratic People\'s Republic of Korea', 'KP', 'PRK', '408', '850', '.kp'],
            ['Northern Mariana Islands', 'Northern Mariana Islands', 'MP', 'MNP', '580', '1+670', '.mp'],
            ['Norway', 'Kingdom of Norway', 'NO', 'NOR', '578', '47', '.no'],
            ['Oman', 'Sultanate of Oman', 'OM', 'OMN', '512', '968', '.om'],
            ['Pakistan', 'Islamic Republic of Pakistan', 'PK', 'PAK', '586', '92', '.pk'],
            ['Palau', 'Republic of Palau', 'PW', 'PLW', '585', '680', '.pw'],
            ['Palestine', 'State of Palestine (or Occupied Palestinian Territory)', 'PS', 'PSE', '275', '970', '.ps'],
            ['Panama', 'Republic of Panama', 'PA', 'PAN', '591', '507', '.pa'],
            ['Papua New Guinea', 'Independent State of Papua New Guinea', 'PG', 'PNG', '598', '675', '.pg'],
            ['Paraguay', 'Republic of Paraguay', 'PY', 'PRY', '600', '595', '.py'],
            ['Peru', 'Republic of Peru', 'PE', 'PER', '604', '51', '.pe'],
            ['Phillipines', 'Republic of the Philippines', 'PH', 'PHL', '608', '63', '.ph'],
            ['Pitcairn', 'Pitcairn', 'PN', 'PCN', '612', NULL, '.pn'],
            ['Poland', 'Republic of Poland', 'PL', 'POL', '616', '48', '.pl'],
            ['Portugal', 'Portuguese Republic', 'PT', 'PRT', '620', '351', '.pt'],
            ['Puerto Rico', 'Commonwealth of Puerto Rico', 'PR', 'PRI', '630', '1+939', '.pr'],
            ['Qatar', 'State of Qatar', 'QA', 'QAT', '634', '974', '.qa'],
            ['Reunion', 'R&eacute;union', 'RE', 'REU', '638', '262', '.re'],
            ['Romania', 'Romania', 'RO', 'ROU', '642', '40', '.ro'],
            ['Russia', 'Russian Federation', 'RU', 'RUS', '643', '7', '.ru'],
            ['Rwanda', 'Republic of Rwanda', 'RW', 'RWA', '646', '250', '.rw'],
            ['Saint Barthelemy', 'Saint Barth&eacute;lemy', 'BL', 'BLM', '652', '590', '.bl'],
            ['Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '654', '290', '.sh'],
            ['Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'KN', 'KNA', '659', '1+869', '.kn'],
            ['Saint Lucia', 'Saint Lucia', 'LC', 'LCA', '662', '1+758', '.lc'],
            ['Saint Martin', 'Saint Martin', 'MF', 'MAF', '663', '590', '.mf'],
            ['Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'PM', 'SPM', '666', '508', '.pm'],
            ['Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VC', 'VCT', '670', '1+784', '.vc'],
            ['Samoa', 'Independent State of Samoa', 'WS', 'WSM', '882', '685', '.ws'],
            ['San Marino', 'Republic of San Marino', 'SM', 'SMR', '674', '378', '.sm'],
            ['Sao Tome and Principe', 'Democratic Republic of S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'ST', 'STP', '678', '239', '.st'],
            ['Saudi Arabia', 'Kingdom of Saudi Arabia', 'SA', 'SAU', '682', '966', '.sa'],
            ['Senegal', 'Republic of Senegal', 'SN', 'SEN', '686', '221', '.sn'],
            ['Serbia', 'Republic of Serbia', 'RS', 'SRB', '688', '381', '.rs'],
            ['Seychelles', 'Republic of Seychelles', 'SC', 'SYC', '690', '248', '.sc'],
            ['Sierra Leone', 'Republic of Sierra Leone', 'SL', 'SLE', '694', '232', '.sl'],
            ['Singapore', 'Republic of Singapore', 'SG', 'SGP', '702', '65', '.sg'],
            ['Sint Maarten', 'Sint Maarten', 'SX', 'SXM', '534', '1+721', '.sx'],
            ['Slovakia', 'Slovak Republic', 'SK', 'SVK', '703', '421', '.sk'],
            ['Slovenia', 'Republic of Slovenia', 'SI', 'SVN', '705', '386', '.si'],
            ['Solomon Islands', 'Solomon Islands', 'SB', 'SLB', '090', '677', '.sb'],
            ['Somalia', 'Somali Republic', 'SO', 'SOM', '706', '252', '.so'],
            ['South Africa', 'Republic of South Africa', 'ZA', 'ZAF', '710', '27', '.za'],
            ['South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239', '500', '.gs'],
            ['South Korea', 'Republic of Korea', 'KR', 'KOR', '410', '82', '.kr'],
            ['South Sudan', 'Republic of South Sudan', 'SS', 'SSD', '728', '211', '.ss'],
            ['Spain', 'Kingdom of Spain', 'ES', 'ESP', '724', '34', '.es'],
            ['Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'LK', 'LKA', '144', '94', '.lk'],
            ['Sudan', 'Republic of the Sudan', 'SD', 'SDN', '729', '249', '.sd'],
            ['Suriname', 'Republic of Suriname', 'SR', 'SUR', '740', '597', '.sr'],
            ['Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'SJ', 'SJM', '744', '47', '.sj'],
            ['Swaziland', 'Kingdom of Swaziland', 'SZ', 'SWZ', '748', '268', '.sz'],
            ['Sweden', 'Kingdom of Sweden', 'SE', 'SWE', '752', '46', '.se'],
            ['Switzerland', 'Swiss Confederation', 'CH', 'CHE', '756', '41', '.ch'],
            ['Syria', 'Syrian Arab Republic', 'SY', 'SYR', '760', '963', '.sy'],
            ['Taiwan', 'Republic of China (Taiwan)', 'TW', 'TWN', '158', '886', '.tw'],
            ['Tajikistan', 'Republic of Tajikistan', 'TJ', 'TJK', '762', '992', '.tj'],
            ['Tanzania', 'United Republic of Tanzania', 'TZ', 'TZA', '834', '255', '.tz'],
            ['Thailand', 'Kingdom of Thailand', 'TH', 'THA', '764', '66', '.th'],
            ['Timor-Leste (East Timor)', 'Democratic Republic of Timor-Leste', 'TL', 'TLS', '626', '670', '.tl'],
            ['Togo', 'Togolese Republic', 'TG', 'TGO', '768', '228', '.tg'],
            ['Tokelau', 'Tokelau', 'TK', 'TKL', '772', '690', '.tk'],
            ['Tonga', 'Kingdom of Tonga', 'TO', 'TON', '776', '676', '.to'],
            ['Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TT', 'TTO', '780', '1+868', '.tt'],
            ['Tunisia', 'Republic of Tunisia', 'TN', 'TUN', '788', '216', '.tn'],
            ['Turkey', 'Republic of Turkey', 'TR', 'TUR', '792', '90', '.tr'],
            ['Turkmenistan', 'Turkmenistan', 'TM', 'TKM', '795', '993', '.tm'],
            ['Turks and Caicos Islands', 'Turks and Caicos Islands', 'TC', 'TCA', '796', '1+649', '.tc'],
            ['Tuvalu', 'Tuvalu', 'TV', 'TUV', '798', '688', '.tv'],
            ['Uganda', 'Republic of Uganda', 'UG', 'UGA', '800', '256', '.ug'],
            ['Ukraine', 'Ukraine', 'UA', 'UKR', '804', '380', '.ua'],
            ['United Arab Emirates', 'United Arab Emirates', 'AE', 'ARE', '784', '971', '.ae'],
            ['United Kingdom', 'United Kingdom of Great Britain and Nothern Ireland', 'GB', 'GBR', '826', '44', '.uk'],
            ['United States', 'United States of America', 'US', 'USA', '840', '1', '.us'],
            ['United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UM', 'UMI', '581', NULL, NULL],
            ['Uruguay', 'Eastern Republic of Uruguay', 'UY', 'URY', '858', '598', '.uy'],
            ['Uzbekistan', 'Republic of Uzbekistan', 'UZ', 'UZB', '860', '998', '.uz'],
            ['Vanuatu', 'Republic of Vanuatu', 'VU', 'VUT', '548', '678', '.vu'],
            ['Vatican City', 'State of the Vatican City', 'VA', 'VAT', '336', '39', '.va'],
            ['Venezuela', 'Bolivarian Republic of Venezuela', 'VE', 'VEN', '862', '58', '.ve'],
            ['Vietnam', 'Socialist Republic of Vietnam', 'VN', 'VNM', '704', '84', '.vn'],
            ['Virgin Islands, British', 'British Virgin Islands', 'VG', 'VGB', '092', '1+284', '.vg'],
            ['Virgin Islands, US', 'Virgin Islands of the United States', 'VI', 'VIR', '850', '1+340', '.vi'],
            ['Wallis and Futuna', 'Wallis and Futuna', 'WF', 'WLF', '876', '681', '.wf'],
            ['Western Sahara', 'Western Sahara', 'EH', 'ESH', '732', '212', '.eh'],
            ['Yemen', 'Republic of Yemen', 'YE', 'YEM', '887', '967', '.ye'],
            ['Zambia', 'Republic of Zambia', 'ZM', 'ZMB', '894', '260', '.zm'],
            ['Zimbabwe', 'Republic of Zimbabwe', 'ZW', 'ZWE', '716', '263', '.zw'],
        ];

        foreach ($countries as $country){
            DB::table('countries')->insert([
                'name' => $country[0],
                'long_name' => $country[1],
                'iso_2' => $country[2],
                'iso_3' => $country[3],
                'iso_number' => $country[4],
                'calling_code' => $country[5],
                'cctld' => $country[6],
            ]);
        }
    }
}
